### ISSUE TITLE
GCP GKE "Default Service Account in Use" does not detect default account

### ISSUE THREAD

**Issue by mmmds** [nccgroup/ScoutSuite#1143]
Rule "Default Service Account in Use" for GCP GKE expects the service account to be equal "default" to trigger the finding.
`providers/gcp/rules/findings/kubernetesengine-default-service-account-used.json:`
```
    "conditions": [
        "and",
        [
            "kubernetesengine.projects.id.zones.id.clusters.id.service_account",
            "equal",
            "default"
        ]
    ],
```
According to the [documentation](https://cloud.google.com/compute/docs/access/service-accounts#default_service_account),  in the gcloud API a default service account has format `PROJECT_NUMBER-compute@developer.gserviceaccount.com`. The same can be also observed by using gcloud cli:
```
$ gcloud container clusters describe [...] --zone europe-west3-a
[...]
nodeConfig:
[...]
  serviceAccount: [...]-compute@developer.gserviceaccount.com
[...]
```

As the result, the rule does not detect usage of the default service account. To correctly detect the issue, the rule should check if `serviceAccount` matches the format `PROJECT_NUMBER-compute@developer.gserviceaccount.com`.

**Comment by j4v** [comment]
Thanks @mmmds this has been on the radar lately, I'll look into remediating.

**Comment by x4v13r64** [comment]
This issue is incorrect, the value evaluated by SS is https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#autoprovisioningnodepooldefaults, which equals `default` when the default SA is used to launch new nodes. 

I'm unsure what GCP does in the backend, but if it's the default SA the value is `default`, otherwise it's the configured SA's email.
