### ISSUE TITLE
Fails to list RDS tags for instances hosted in non-commercial region

### ISSUE THREAD

**Issue by zanesewell** [nccgroup/ScoutSuite#1183]
**Describe the bug**

RDS ARN is being constructed in rds.py script (Line 52 as of release 5.10.2) with hard-coded partition resulting in a client error when calling client.list_tags_for_resource against instances hosted in non-commercial regions.

Error = _ERROR rds.py L51: Failed to get db instance tags for test-1: An error occurred (InvalidParameterValue) when calling the ListTagsForResource operation: Invalid resource name:  arn:**aws**:rds:us-gov-west-1:123456789:db:test-1_

Actual ARN = arn:**aws-us-gov**:rds:us-gov-west-1:123456789:db:test-1
Please provide:

**To Reproduce**
CLI input: scout.py aws -r us-gov-west-1

**Comment by j4v** [comment]
@lowSoA can you have a look at this please?

**Comment by lowSoA** [comment]
Indeed this seems to be an issue since the partition part of the ARN is hardcoded as `aws` in the [master branch](https://github.com/nccgroup/ScoutSuite/blob/db827e3d8e36e3bc7adcb8c62f2453960353c2ef/ScoutSuite/providers/aws/resources/rds/instances.py#L27). However, a correct parsing for RDS instances is already implemented in the [develop branch](https://github.com/nccgroup/ScoutSuite/blob/289d8830b01a1da4cca814202afb383867051620/ScoutSuite/providers/aws/resources/rds/instances.py#L27).

There should be a small change to the [RDS facade (rds.py)](https://github.com/nccgroup/ScoutSuite/blob/289d8830b01a1da4cca814202afb383867051620/ScoutSuite/providers/aws/facade/rds.py#L52) to get the already parsed ARN and gather the tags.

**Comment by j4v** [comment]
@lowSoA could you have a quick look to ensure the partition isn't hardcoded in any of the ARNs in the `develop` branch? Unless this is something you already did, in which case we can close this issue?

**Comment by lowSoA** [comment]
This seems to be the only case where a hardcoded partition is used.

@zanesewell could you please test [this PR](https://github.com/nccgroup/ScoutSuite/pull/1187)?

**Comment by zanesewell** [comment]
@lowSoA that commit appears to have resolved the issue. Thanks!

**Comment by j4v** [comment]
Closing as fixed, cheers @lowSoA
