### ISSUE TITLE
GCP Multi-Project Scanning with single service account

### ISSUE THREAD

**Issue by rtomlinson-latacora** [nccgroup/ScoutSuite#120]
I would like ScoutSuite to be able to scan multiple projects with a single service account and compile a single report. Much like it does with a user account. Happy to work on this issue. Thank you.

https://cloud.google.com/sdk/gcloud/reference/projects/list
https://stackoverflow.com/questions/35479025/cross-project-management-using-service-account

**Comment by j4v** [comment]
Further discussions in https://github.com/nccgroup/ScoutSuite/issues/80.

@rtomlinson-latacora if you'd be interested in working on this feature, it should involve some [relatively simple] changes to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/provider.py. The `_get_projects` currently implements this for user accounts.

**Comment by rtomlinson-latacora** [comment]
Sounds great and thank you. I'll take a look at the code and get a PR to you.

**Comment by rtomlinson-latacora** [comment]
Hmm, so it should be pretty straightforward. The only thing that's causing service accounts to only scan the project in which the service account itself was created is line 157 on https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/provider.py. It filters based on `parent_id`. Maybe we can default to having a flag for the service account and have all the projects pulled? I'm not too sure how nccgroup likes to do these things so open to suggestions.

**Comment by rtomlinson-latacora** [comment]
I'm assuming that `parent_type` will only be set to `project` if the `--project-id` arg is set on the cli

**Comment by j4v** [comment]
> I'm assuming that `parent_type` will only be set to `project` if the `--project-id` arg is set on the cli

Not exactly, if you run Scout with `--service-account` and provide credentials through the `--key-file` argument, the credentials JSON file contains the `project_id` parameter which is used here.
If you provide the additional `--project-id` argument, that allows setting another project to scan for the SA.

The issue here is that you need a way to determine all the projects to which a SA has access. 
For a user that's pretty easy as if it has IAM privileges at the Organization level, the `_get_projects` method will be able to run `resource_manager_client_v1.projects()` and get a list of all the projects in that Org.

So in order to have similar functionality for a SA, we'd have to implement something that allows enumerating the projects to which the SA has access.

**Comment by rtomlinson-latacora** [comment]
I was able to get scanning all projects that a SA has access to working with my PR the same way that a user account with organization level access does.
I should have clarified what I meant a little more with `parent_type` being set to `project`. `parent_type` gets set to `project` when either `--project-id` is passed on the command line or when the `if/else` clauses make it to `else` clause. Here the `project_id` pulled from the `google.auth` step is used to set `self.project_id`. This `else` clause also sets `parent_type` to `project` which is used in `_get_projects()`

**Comment by j4v** [comment]
Working on this, the code merged in `develop` has a few issues.

**Comment by rtomlinson-latacora** [comment]
Anything I can help with?

**Comment by rtomlinson-latacora** [comment]
I found a reference error in the code that I pushed. Did you already fix
it? Line 90, ScoutSuite/providers/gcp/provider.py. self.service_account
should just be service_account.

**Comment by j4v** [comment]
> I found a reference error in the code that I pushed. Did you already fix it? Line 90, ScoutSuite/providers/gcp/provider.py. self.service_account should just be service_account.

Yep, saw that one.

The code you wrote to pull all the projects works great, but I'm seeing an issue with how it's later processed. Working on it, should have a PR ready today.

**Comment by j4v** [comment]
@rtomlinson-latacora I've pushed the https://github.com/nccgroup/ScoutSuite/pull/152 PR for this.

I've made a few changes to the scanning logic:
- If a Project, Folder or Organization is provided through the CLI, then that's what will be scanned
- Otherwise, if a Project is inferred (default project configured for a user or set in the Service Account credentials file), then that project will be scanned
- Otherwise, we pull all the Projects to which the user/Service Account has access to, and we'll scan all of them (this is the code you contributed)

**Comment by j4v** [comment]
Closing, implemented in `develop`.

**Comment by j4v** [comment]
Reopening this issue in relation to discussions in https://github.com/nccgroup/ScoutSuite/pull/152.

**Comment by j4v** [comment]
Closing, fixed in `develop`
