### ISSUE TITLE
Azure --cli issue on Centos 7

### ISSUE THREAD

**Issue by Selam-Berhane** [nccgroup/ScoutSuite#1394]
I installed ScoutSuite and azure-cli  on Centos 7 and I signed in with az login  , which was successful and then I run 
 scout azure --cli  it gives me the following error:

 **ERROR __main__.py L229: Initialization failure: 'ARMPipelineClient' object has no attribute 'config'**

To Reproduce

I followed the installation guide from the ScoutSuite wiki, then I installed azure-cli. From there I do the following:

az login (login was successful)

I then run  _scout azure --cli_
It then gives me the error message that I described above.
Additional context

scout  azure --cli
 INFO Launching Scout
 INFO Authenticating to cloud provider
 **ERROR __main__.py L229: Initialization failure: 'ARMPipelineClient' object has no attribute 'config'**

Versions:
python 3.8 
Scout Suite 5.10.2

**Comment by fernando-gallego** [comment]
Hi,

This has been fixed in the develop branch by updating the authentication libraries and functions to use the new versions.

Changes have not yet made it to master; please give it a try with the develop branch to see if the error persists. Also check the new **requirements.txt** file which contains updated versions for multiple packages. These will be needed for the upgraded authentication scheme to work as expected.
