### ISSUE TITLE
HTML Report is not getting open please find the attached screenshot

### ISSUE THREAD

**Issue by Linish2020** [nccgroup/ScoutSuite#1403]
![image](https://user-images.githubusercontent.com/75070598/156327930-388160fb-f836-4525-bcce-7f628c25abfe.png)

**Comment by fernando-gallego** [comment]
Hi,

Could you provide more details about the issue as per the issue template?

**Describe the bug**

Please provide:

- A clear and concise description of what the bug is.
- Console output using the `--debug` argument.
- If possible, the errors JSON file generated at the end of execution (the CLI output will provide the path to this file). The file can be sent to <scoutsuite@nccgroup.com> to avoid including sensitive content in the GitHub issue.

**To Reproduce**

Please provide:

- The **exact** CLI parameters used to run Scout Suite.
- Any specific configuration within the cloud account which might have lead to the issue.

**Additional context**

Add any other context about the problem here.

**Comment by x4v13r64** [comment]
Pretty sure this is a non-issue / caused by some local error / trying to access a report via the network. The screenshot is the result of the HTML artifacts not being loaded.
