### ISSUE TITLE
Cross Account Assume Role Access support missing in Scout2

### ISSUE THREAD

**Issue by vvkdby** [nccgroup/ScoutSuite#28]
I can setup my AWS EC2 instance with the role that has the permissions to assume any role it wants, as described in [this post](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-cli/). Specifically, if I have a policy like the following:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": "*"
        }
    ]
}
```
I can run aws cli commands with just the role_arn and external_id. But I cannot run Scout2 with a profile containing just the role_arn and external_id, since it requires the presence of `aws_secret_access_key` and `aws_access_key_id`. Some shallow surfing of the source code tells me that [this line seems to be the problem](https://github.com/nccgroup/Scout2/blob/master/AWSScout2/__main__.py#L56). ( [This line also seems related](https://github.com/nccgroup/opinel/blob/master/opinel/utils/credentials.py#L451) )

Scout2 should have similar behavior as aws cli in this case, i.e. it should be okay without `aws_secret_access_key`.

**Comment by j4v** [comment]
Closing this issue as we no longer rely on opinel for AWS authentication. You should now setup authentication as per usual. If you pass a named profile to scout (`--profile` argument) then that's what scout will use, otherwise it will use boto's standard evaluation logic (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html).

See https://github.com/nccgroup/ScoutSuite/issues/9 for change.
