### ISSUE TITLE
Incorrect CMD when not running through CLI

### ISSUE THREAD

**Issue by thommor** [nccgroup/ScoutSuite#407]
When running ScoutSuite through another python program (as an import) the `cmd` in `last_run` is the command of the overarching program, not what would of been ran if using ScoutSuite from the CLI.

It would be useful that if ScoutSuite is ran as an import that the `cmd` is set to what would have been run if running from the CLI.

**Comment by j4v** [comment]
Would it work better if instead of the CLI value (taken from `sys.argv`) it was a dict of the non-`None` values passed to `_run()`?

In the report, instead of displaying "Command", we could display these values.

**Comment by thommor** [comment]
@j4v Yeah that works for me

**Comment by j4v** [comment]
@thommor looks something like this:

![sc_2019-05-17_16h09m05s](https://user-images.githubusercontent.com/4206926/57933713-4481fe00-78be-11e9-8e2e-e604ca2fbdda.jpg)

I don't think it looks as "nice" as before especially since the parameter names are the ones in the code not the CLI but it does the job.

Comments/Suggestions?

**Comment by j4v** [comment]
Closing as merged into `develop`.
