### ISSUE TITLE
Feature Request: Quickstart guide

### ISSUE THREAD

**Issue by Viss** [nccgroup/ScoutSuite#664]
Hi! 
We do assessments for folks that heavily utilize aws, but so infrequently things tend to change underneath us between assessments, so to keep abreast of any changes aws makes in the mfa/iam/cli world, it would be super super handy to have a quick and dirty  'how to make it go in 60 seconds' set of instructions available for reference!

something like:
- starting point is: creds from customer, with mfa (say, google authenticator)
- how to setup barebones aws environment for auth with those parameters
- how to change roles (because of course, the default role you get can't do anything)
- how to then use that session to launch scoutsuite

thanks in advance!

**Comment by j4v** [comment]
I believe we already have this:
- How to install - https://github.com/nccgroup/ScoutSuite/wiki
- How to run for AWS - https://github.com/nccgroup/ScoutSuite/wiki/Amazon-Web-Services
  - Also referrenced in that entry, the boto doc for authentication https://github.com/nccgroup/ScoutSuite/wiki/Amazon-Web-Services

MFA/IAM/CLI have been pretty static for the past years so that shouldn't be an issue.
