### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by heydonovan** [nccgroup/ScoutSuite#713]
We currently copy the latest release artifact into our own private repo, and then run a custom GitLab pipeline to build/deploy the image. This is fine for now, but are there currently any plans to push to Docker Hub so we can pull the image down without having to build it first? I'm willing to help write some GitHub Actions to achieve this. :)

**Comment by j4v** [comment]
We haven't done this as we don't want to maintain is [manually], and tbh we're also a bit afraid of having to address user issues with an image we provide. 

If this can be done reliably/automatically, we'd consider it for sure.

**Comment by j4v** [comment]
Closing due to lack of feedback.

**Comment by sean-ersw** [comment]
If I may suggest a re-opening of this - with a valid reason (I Hope!)

We want to run scoutsuite in a scheduled pipeline daily (Gitlab) - but just the build of the Dockerfile takes 22mins or more! Thats a crazy amount of CI minutes to spend on just assembling the tooling :) 

As with many CI engines (Gitlab, Github Actions, etc) we use docker based runners and can normally just pull the image (seconds rather than 22 minutes) and execute the job. 

But with scoutsuite we are forced to either run yet another pipeline to make regular builds of scoutsuite and push them them to a private registry or build the image inline every time which takes 4-5 times longer than running the actual scan :)

**Comment by j4v** [comment]
@sean-ersw for now you may want to use https://hub.docker.com/r/rossja/ncc-scoutsuite (https://github.com/rossja/ncc-scoutsuite).

@rossja is planned to port the content to this repository but there's no ETA AFAIK. @rossja any input?

**Comment by sean-ersw** [comment]
Haha - typical! I went through a half-dozen image repos and they all seemed half-baked - so I rolled my own "half-baked" and then you point out a good one! :)

Great to know its on the radar!

**Comment by rossja** [comment]
I'll work on it this week, so let's say Friday for PR ETA. Sorry for the delay

**Comment by j4v** [comment]
This is now implemented in `develop`, see https://github.com/nccgroup/ScoutSuite/pull/775.
