### ISSUE TITLE
Properly implement Azure authentication

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#81]
Properly implement authentication for the Azure provider. Current implementation in `providers/azure/provider.py` only supports service principals [in a limited manner].

Refs:
https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python
https://azure.microsoft.com/en-ca/resources/samples/data-lake-analytics-python-auth-options/
https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki
https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-scenarios#application-types-and-scenarios
https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory?view=azure-python

Once this is done, update README to explain how to authenticate.

**Comment by mitsuo0114** [comment]
Does this ticket intend to append "App Registration" authentication like tenable do?[1] or implement 
ManagementClients like providers/aws/provider.py and official sample code?[2]

Because I have development experience of Azure REST API with Service Principal, I may be able to contribute to this ticket.

[1] https://docs.tenable.com/other/azure/Content/Auditing.htm
[2] https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py

**Comment by zer0x64** [comment]
Implemented in #112, closing

**Comment by j4v** [comment]
Testing this out I see that credentials are prompted interactively:

![sc_2019-02-01_10h04m56s](https://user-images.githubusercontent.com/4206926/52113168-e845e780-2608-11e9-8bf2-f98d2fac476c.jpg)

As for AWS/GCP, all CLI parameters should be passed directly. The rationale for this is that asking for credentials interactively doesn't allow to run Scout programatically.

One option would be to add a `--interactive` flag to *also* support how it's currently implemented, but we really need to be able to run Scout from code.

**Comment by j4v** [comment]
@zer0x64 I think this can be closed now?

**Comment by zer0x64** [comment]
Yes!
