### ISSUE TITLE
Rationale / Risk of "Policy that Allows Non STS Action" rule for AWS,  unclear 

### ISSUE THREAD

**Issue by rams3sh** [nccgroup/ScoutSuite#823]
I found some findings from Scoutsuite scan on my personal account pertaining to following rules :-

1.  Inline group Policy Allows Non STS Action
2. Inline role Policy Allows Non STS Action
3.  Inline user Policy Allows Non STS Action
4.  Managed Policy Allows Non STS Action

I checked the rationale and it gives the following detail.
```
**Description**
This configuration goes against organizational policies.

**References**
https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html
```

I checked the provided link but I was unable to map the risk / rationale of the findings of the above mentioned category.
Also the rationale lacks clarity on the policies which the identified flagged resources go against.

Would be really nice , if someone can provide some info regarding the above 4 rules. Or update the rule's rationale for it to be self explanatory.

**Comment by j4v** [comment]
You'd want to ensure policies attached to users only allow for STS actions (namely role assumption) if you implement "principle of least privilege" by only granting significant privileges to roles, and then allowing users to assume those roles as required by their responsibilities. e.g. instead of granting EC2 administrative access to any user or group, you'd create a role with said access, and allow users/groups to assume the role when required. This can help control who is using what privileges when / for what purposes.

These rules are only included in the detailed ruleset as they are not always something you'd be concerned with / would want to validate.

**Comment by j4v** [comment]
TODO:

- [ ] Add the above to the rationale
- [ ] Add an `id_suffix` to the rules

**Comment by j4v** [comment]
This is implemented by https://github.com/nccgroup/ScoutSuite/pull/842.
