### ISSUE TITLE
Issue opening Azure report

### ISSUE THREAD

**Issue by jrugge1** [nccgroup/ScoutSuite#851]
I tried this with the `--services ` flag for `"aad", "appservice", "arm", "keyvault", "network", "securitycenter", "sqldatabase", "storageaccounts", "virtualmachines"` services. I think it is the aad service that gets stuck which could be because we have a lot of active directory data, but given that there is only one rule `aad-guest-users.json` it does not make a lot of sense as to what might be taking that long. Does the code crawl through the active directory to fetch data?

> # Update - 

I let scout run on one of my systems for 1.5 days and I got a file that was 2.05 GB which might explain why the HTML wasn't loading and why the other systems were also taking forever to complete the scan.

_Originally posted by @reach4bawer in https://github.com/nccgroup/ScoutSuite/issues/698#issuecomment-609448727_

**Comment by j4v** [comment]
Couple of questions:
- Are you running the latest version? The issue you mention with the AD users should have been fixed by https://github.com/nccgroup/ScoutSuite/pull/734.
- Do you have a very large number of subscriptions? If you, you may be running into https://github.com/nccgroup/ScoutSuite/issues?q=is%3Aissue+is%3Aopen+large. If it's the case, you should run against individual subscriptions.
- You may be running into https://github.com/nccgroup/ScoutSuite/issues/793, which Should be resolved by https://github.com/nccgroup/ScoutSuite/pull/848.

**Comment by jrugge1** [comment]
Yes my local repo is uptown date so I am on the latest version. 

I only ran it against one of our azure subscriptions. 

No I think that is a different issue. The scan completes, however the issue I am having is that after the report generator starts the browser just hangs and stays stuck with the message "Loading Data, This May take a while" and does not open.

**Comment by jrugge1** [comment]
Ok, thanks although it looks like this bug fix has not yet been completed and merged in 848. unless I'm missing something not sure what I need to do here to fix this.

**Comment by j4v** [comment]
> Ok, thanks although it looks like this bug fix has not yet been completed and merged in 848

The PR should resolve the https://github.com/nccgroup/ScoutSuite/issues/793 issue.

**Comment by j4v** [comment]
Closing this issue as a duplicate.
