### ISSUE TITLE
Leverage boto3 for authentication

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#9]
The current implementation for authentication could/should rely solely on boto3 and not on any custom code, AKA remnants of Opinel.

It should be validated that this wouldn't create any issues with MFA.

**Comment by vifor2** [comment]
Current branch : ­[refactoring/9-leverage-boto3-for-authentication](https://github.com/nccgroup/ScoutSuite/tree/refactoring/9-leverage-boto3-for-authentication)

TODO : Replace the contents of `crendentials.py` with an implementation of authentication via boto3, reading credentials from a CSV file will be dropped by doing so.

**Comment by vifor2** [comment]
To make sure I don't forget stuff I like to write it down, and since I'm not working on this issue alone I figure I'll write my current thoughts here :
- Other than for the tests, the only functions from `credentials.py` being called is `read_creds`, which greatly simplifies our work since by a first look at  `credentials.py` we could've thought that there is much more to do since there are 15 functions defined over 533 lines.
![image](https://user-images.githubusercontent.com/17322874/53699608-3856cc00-3db8-11e9-8793-00328ebe5248.png)
- `read_creds` : Inputs : profile_name, ~~csv_file~~, mfa_serial_arg, mfa_code, force_init. Outputs : dict containing : AccessKeyId {str}, SecretAccessKey {str}, SessionToken {str}, Expiration {datetime}.

**Comment by j4v** [comment]
You're right that only `read_creds` is explicitly called, but most of the functions in `credentials.py` are then used by `read_creds` (`read_creds` implements the logic, the other functions do the actual IAM work).

This said I'd think they can all be scraped for a much simpler implementation:
```python
# in this case a profile is explicitly stated
if args.profile:
    session = boto3.Session(profile_name='<foo>')
# otherwise the boto logic is used, which should work natively for EC2, ECS, Lambda, etc
# logic defined here https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials
else: 
       session = boto3.Session()       
```

The `session` can then be reused (instead of "credentials" as currently done) in `connect_service` (https://github.com/nccgroup/ScoutSuite/blob/1b4b502822e1b4f9bdc5cf4bfd394a60202e9461/opinel/utils/aws.py#L31):

```python
# Any clients created from the above session will use those credentials
s3_client = session.client('s3')
```

**Comment by vifor2** [comment]
### Update
Credentials.py successfully removed, now using boto3.Session for both users with profiles and those without.

TODO: MFA!

**Comment by j4v** [comment]
Closing as this has been merged into `develop`.
