### ISSUE TITLE
feature request - AWS SecurityHub integration

### ISSUE THREAD

**Issue by gebailey** [nccgroup/ScoutSuite#92]
AWS recently announced SecurityHub at re:Invent, and it appears to be a dashboard that presents security findings originating from third-party security tools, or from manually imported findings.

It'd be great to see ScoutSuite optionally produce a JSON output file containing findings in the AWS SecurityHub findings format that could be directly imported into SecurityHub, or perhaps ScoutSuite could directly import the findings via the SecurityHub API, bypassing the intermediate JSON file.

I'm working on a script to manually generate SecurityHub findings for a subset of ScoutSuite findings, but I imagine this could prove useful to a greater audience, at least for AWS environments.

* [SecurityHub documentation](https://aws.amazon.com/security-hub/)
* [SecurityHub findings format](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html)

**Comment by j4v** [comment]
> I'm working on a script to manually generate SecurityHub findings for a subset of ScoutSuite findings, but I imagine this could prove useful to a greater audience, at least for AWS environments.

thanks @gebailey, if you do write such a script please do share and we can think of how to integrate in Scout? Or maybe have a folder with tools/integrations?

**Comment by klauern** [comment]
Oh, this would be useful as well for us.  Any chance you have a branch or fork that points to this integration?  We might be able to help with it.

**Comment by j4v** [comment]
@JJmako any details you can share?

**Comment by JJmako** [comment]
Hi guys. I am doing this work right now. I can't continue developing this today (because some work tasks >.<) but I will continue next Monday.
I am doing an external tool (a .py) for parse the data. The amount of information is really huge, so all help is welcome.

I will upload my local branch today (I don't have much done yet).

Thank you for your interest @klauern , I expect to have this ready as soon as possible.

**Comment by rracterr** [comment]
possibly better design... why not simply call batch_import_findings and shove them straight into the security hub api of the account being scanned?   

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/securityhub.html#SecurityHub.Client.batch_import_findings

**Comment by j4v** [comment]
@rracterr I believe that's what is being done.

i.e.:
- take a JSON results file
- convert findings to Security Hub format
  - these can be outputted or processed if there's additional requirements
- upload them to Security Hub through the API

**Comment by rscottbailey** [comment]
This is the approach used at GoDaddy. With respect to "...these can be outputted or processed if there's additional requirements", here are some of the transformations we make during this process. This is mentioned to get people thinking enabling them, not because I want to see it all implemented in the first iteration. ;-)

* "upload" actually is "scan, update, overwrite [using batch_import_findings]" so that properties such as CreatedAt, FirstObservedAt, and additional stuff used to manage exception tracking are preserved;
* finding ids are generated mechanically from path most of the time, but we override some where the result is nonsensical or duplicative or excessively long-winded;
* we are investigating using name tags instead of object ids for some findings so that rolling an instance (for example) doesn't generate a "new" finding that really isn't;
* we do a lot of severity twiddling... we adjust some findings because our policy diverges from the default severity; some are adjusted based on presence of specific tags on the related resource; findings with approved exceptions are reduced to 0 (Informational)

**Comment by j4v** [comment]
@rscottbailey any code you can share?

**Comment by j4v** [comment]
Closing, this is now implemented in `develop`. See https://github.com/nccgroup/ScoutSuite/tree/develop/tools#aws_security_hub_exportpy.
