### ISSUE TITLE
bug - CloudTrail and service filtering

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#98]
When running an AWS scan using the `--services` flag, the CloudTrail service is always scanned even if it isn't selected.

**Comment by Aboisier** [comment]
After an investigation, CloudTrail is not always scanned. The "Processing CloudTrail config..." log is part of the preprocessing. If I add a guard as such

```
if 'cloudtrail' not in self.service_list:
        return
```

at the beginning of the preprocessing method, then we get a bunch of rules errors.

> Current path: ['cloudtrail']
> 'DuplicatedGlobalServiceEvents'
> Current path: ['cloudtrail']
> [WinError 87] The parameter is incorrect
> Failed to process rule defined in cloudtrail-duplicated-global-services-logging.json
> Current path: ['cloudtrail']
> 'IncludeGlobalServiceEvents'
> Current path: ['cloudtrail']
> [WinError 87] The parameter is incorrect
> Failed to process rule defined in cloudtrail-no-global-services-logging.json
> Current path: ['cloudtrail']
> 'data_logging_trails_count'
> Current path: ['cloudtrail']
> [WinError 87] The parameter is incorrect
> Failed to process rule defined in cloudtrail-no-data-logging.json

This is because the post-processing sets some attributes. I suggest we add move logging to clarify what is happening at the begging of each part of the process (fetching configs, pre-processing, processing, post-processing) so that the user isn't confused.

**Comment by j4v** [comment]
You're right, as it gets highlighted even though there are no resources:

![sc_2019-01-26_16h21m00s](https://user-images.githubusercontent.com/4206926/51789186-80198080-2186-11e9-812f-179213ca912b.jpg)

Adding logging would be good, but I think your second point should help solve this appropriately.

**Comment by Aboisier** [comment]
Closing, implemented in #124.

**Comment by j4v** [comment]
While CloudTrail is no longer seen in the dashboard, I do still get this in execution output:
```
Processing CloudTrail config...
Matching EC2 instances and IAM roles...
```

Just checking that this is expected? Running latest `develop` branch.

**Comment by Aboisier** [comment]
It is expected. Scout does a bunch of processing after having scanned the resources. From my understanding, this is necessary even if there are no resources. If it was not run, the data structure would be inconsistent. Most of the other processing methods do not have logging, this is not specific to CloudTrail.
